// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NGCS_Test_Task.Entity;

namespace NGCS_Test_Task.Entity.Migrations
{
    [DbContext(typeof(AlbumContext))]
    [Migration("20210830125806_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("NGCS_Test_Task.Models.Album", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("albumCensoredName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("albumName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("albumViewUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("artistName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("artistViewUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("artworkUrl100")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("artworkUrl60")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("copyright")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("currency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("genre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("price")
                        .HasColumnType("real");

                    b.Property<DateTimeOffset>("releaseDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("trackCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Albums");
                });
#pragma warning restore 612, 618
        }
    }
}
